version: "2"

plugins:
  duplication:
    enabled: true

    config:
      languages:
        javascript:
          mass_threshold: 1000

        ruby:
          mass_threshold: 80

    exclude_patterns:
      - "spec/**/*"

  grep:
    enabled: true

    config:
      patterns:
        no-trailing-whitespace:
          pattern: \s*$
          annotation: "Don't leave trailing whitespace"
          severity: minor
          categories: Style

        no-tabs:
          pattern: "  "
          annotation: "Don't use hard tabs"
          severity: minor
          categories: Style

    exclude_patterns:
      - "**/*/locales/*.yml"
      - "**/*/*.svg"

  markdownlint:
    enabled: true

exclude_patterns:
  - "**/vendor/"
  - "node_modules/"
  - "development_app/"
  - "spec/decidim_dummy_app/"
  - "coverage/"
