language: ruby

rvm:
 - 2.6.3

addons:
  postgresql: "9.5"

env:
  global:
    - CC_TEST_REPORTER_ID=bb2a496f0bd3c281ad9c7fc934bb3d16284bdd66f13956f7feb283f4958623de
    - BUNDLE_GEMFILE="$TRAVIS_BUILD_DIR/Gemfile"
    - BUNDLE_PATH="$HOME/.bundle"
  matrix:
    - GEM=. DB=postgres

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - cd $GEM;
  - bundle exec rubocop
  - bundle exec erblint app/{cells,views}/**/*.erb
  - bundle exec rake test_app
  - SIMPLECOV=1 CODECOV=1 bundle exec rake

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT